package io.metacake.core.input.system;

import io.metacake.core.common.window.CakeWindow;
import io.metacake.core.input.ActionTrigger;

/**
 * The InputDevice acts as the Interface into any input device.
 * <p>
 * In principle, the InputDevice acts as a means of interfacing with some kind of system level input, such as a
 * Keyboard.
 *
 * @author florence
 * @author rpless
 */
public interface InputDevice {

    /**
     * Shutdown all loops and free resources. This should leave the device in a state such that
     * it can be restarted
     */
    public void shutdown();

    /**
     * Bind this device to the given window.
     * @param w The window for the game
     */
    public void bind(CakeWindow w);

    /**
     * Add an ActionTrigger that will create actions based off events from this InputDevice.
     * @param trigger The ActionTrigger that can create actions from events generated by this device.
     */
    public void addTrigger(ActionTrigger trigger);

    /**
     * Forget all known triggers
     */
    public void releaseTriggers();

    /**
     * when this method returns any loops needed for this device to run should be launched.
     */
    public void startInputLoop();
}